name: image-build-manual

on:
  workflow_dispatch:
    inputs:
      config_name:
        description: 'image to build.. eg terraform-cicd:v1.5.4'
        required: true

jobs:

  image-build-manual:
    runs-on:
      - self-hosted
      - default-k8s-runner-linux-x64
    steps:

      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: build-and-push
        id: build-and-push
        uses: ./.github/actions/build-and-push
        with:
          registry_remote: docker-remote.artifactory-ha.tmc-stargate.com
          registry: devex-dock.artifactory-ha.tmc-stargate.com
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_TOKEN }}
          configs_dir: configs
          config_name: ${{ github.event.inputs.config_name }}
