name: image-build-auto

on:
  push:
    branches:
      - master
      - develop
    paths:
      - configs/**
      # - .github/**

jobs:

  identify-changed-configs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: debug
        shell: bash
        run: |
          echo debug print
          git diff --name-only ${{ github.event.before }} ${{ github.event.after }}
          echo done

      - name: changed-configs
        id: changed-configs
        uses: ./.github/actions/changed-configs
        with:
          INPUT_CONFIGS_DIR: configs
          INPUT_SHA_START: ${{ github.event.before }}
          INPUT_SHA_END: ${{ github.event.after }}

    outputs:
      configs: ${{ steps.changed-configs.outputs.changed_configs }}

  image-build-job:
    runs-on: ubuntu-latest
    needs: identify-changed-configs

    strategy:
      matrix:
        config-name: ${{ fromJson(needs.identify-changed-configs.outputs.configs) }}

    steps:

      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: build-and-push
        id: build-and-push
        uses: ./.github/actions/build-and-push
        with:
          registry_remote: docker-remote.artifactory-ha.tmc-stargate.com
          registry: devex-dock.artifactory-ha.tmc-stargate.com
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_TOKEN }}
          configs_dir: configs
          config_name: ${{ matrix.config-name }}
